spring.application.name=Insight-Auth

#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/InsightAuth
spring.datasource.username=postgres
spring.datasource.password=1234

#JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#JWT
api.security.token.secret=fa1cda0b0124e13264834a11ae1f5de0c0847cb5018df716748e7a58df31a73a